name: prioritease
description: "A task app"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  google_fonts: ^6.2.1
  flutter:
    sdk: flutter
  # Work with http requests
  http: ^1.3.0
  cupertino_http: ^2.0.2  # iOS/macOS
  cronet_http: ^1.3.2     # Android1
  fetch_client: ^1.1.2    # Web
  shared_preferences: ^2.5.1
  encrypt: ^5.0.3
  image_picker: ^1.1.2
  mime: ^2.0.0
  http_parser: ^4.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/
